[test]
coverage = true

coverageReporter = ["text", "lcov"]
coverageDir = "coverage"

coverageSkipTestFiles = true
coveragePathIgnorePatterns = [
  "dist/**",
  "coverage/**",
  "node_modules/**",
]

